### ISSUE TITLE
Feature request: add documentation about `trash restore --ranges`

### ISSUE THREAD

**Issue by j-lakeman** [oberblastmeister/trash-cli#116]
I couldn't find anything about the `--ranges` flag in the documentation. Though it's a quite helpful flag I reckon.

**Comment by oberblastmeister** [comment]
It should show up if you do `trash restore --help`. The longer `--help` shows more info than `--h`.

**Comment by j-lakeman** [comment]
True that. Thanks!

**Comment by honghao71** [comment]
It is not workable in windows pwsh. trash.exe empty --ranges='47..217' got an error: Must match something
